language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
addons:
    apt:
        packages:
            - libasound2-dev
os:
    - linux
    - osx
script:
    - cargo build --verbose
    - cargo test --verbose -j 1
